import { expect, test, type Page } from '@playwright/test'
import { signIn } from './auth'

async function navigate(page: Page, label: string) {
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: label, exact: false }).click()
  if (label === 'Overview') await expect(page.getByText('Controller overview', { exact: true })).toBeVisible()
  else await expect(page.getByRole('heading', { level: 1, name: label, exact: true })).toBeVisible()
}

async function list(page: Page, path: string): Promise<Array<Record<string, any>>> {
  const response = await page.request.get(`/api/v1/${path}`)
  expect(response.status(), await response.text()).toBe(200)
  return (await response.json()).items
}

test('session, authorization and CSRF stay active across the browser boundary', async ({ page, context }) => {
  expect((await page.request.get('/api/v1/overview')).status()).toBe(401)
  expect((await page.request.post('/api/v1/auth/login', {
    headers: { 'X-Auth-Request-User': 'unsigned', 'X-Auth-Request-Role': 'admin' },
  })).status()).toBe(401)
  await signIn(context)
  const denied = await page.request.post('/api/v1/devices', { data: { name: 'Missing CSRF', addresses: [] } })
  expect(denied.status()).toBe(403)
  expect((await list(page, 'devices')).some(item => item.name === 'Missing CSRF')).toBe(false)
  await page.goto('/')
  await expect(page.getByText('Controller overview', { exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Gateway', exact: true })).toHaveValue('fixture-gateway')
  await signIn(context, 'viewer')
  expect((await page.request.get('/api/v1/providers')).status()).toBe(200)
  expect((await page.request.get('/api/v1/gateways')).status()).toBe(200)
  const csrf = (await context.cookies()).find(cookie => cookie.name === 'egressdeck_csrf')!.value
  const forbidden = await page.request.post('/api/v1/gateways', {
    headers: { 'X-CSRF-Token': csrf },
    data: { name: 'Viewer forbidden gateway', endpoint: 'https://forbidden.invalid', adapter: 'dae' },
  })
  expect(forbidden.status()).toBe(403)
  await page.reload()
  await navigate(page, 'Rules')
  await expect(page.getByRole('button', { name: 'New policy', exact: true })).toBeDisabled()
})

test('subscription import publishes through the real API and manual selection reads back', async ({ page, context }, testInfo) => {
  await signIn(context)
  await page.goto('/')
  await navigate(page, 'Subscriptions')
  await page.getByRole('button', { name: 'Add subscription', exact: true }).click()
  await page.getByLabel('Provider name', { exact: true }).fill('Browser imported subscription')
  await page.getByRole('combobox', { name: 'Source type', exact: true }).selectOption('paste')
  await page.getByLabel('Subscription content', { exact: true }).fill('socks5://fixture:password@browser-edge.example:1080#Browser%20edge')
  await page.getByRole('combobox', { name: 'Import format', exact: true }).selectOption('links')
  await page.getByRole('button', { name: 'Add and stage provider', exact: true }).click()
  const card = page.getByRole('article', { name: 'Provider Browser imported subscription', exact: true })
  await expect(card).toBeVisible()
  await expect(card.getByRole('button', { name: 'Apply staged revision', exact: true })).toBeEnabled()
  const provider = (await list(page, 'providers')).find(item => item.name === 'Browser imported subscription')
  expect(provider).toBeDefined()
  const staged = await list(page, `providers/${provider!.id}/revisions`)
  expect(staged).toEqual(expect.arrayContaining([expect.objectContaining({ state: 'staged' })]))
  await card.getByRole('button', { name: 'Apply staged revision', exact: true }).click()
  await expect.poll(async () => (await list(page, `providers/${provider!.id}/revisions`)).some(item => item.state === 'active')).toBe(true)
  await expect(card.getByRole('button', { name: 'Apply staged revision', exact: true })).toBeDisabled()

  await navigate(page, 'Proxies')
  await page.getByRole('button', { name: 'New outbound group', exact: true }).click()
  await page.getByLabel('Outbound group name', { exact: true }).fill('Browser manual exit')
  await page.getByRole('combobox', { name: 'Outbound gateway', exact: true }).selectOption('fixture-gateway')
  await page.getByRole('checkbox', { name: 'Candidate Browser edge', exact: true }).check()
  await page.getByRole('button', { name: 'Create outbound group', exact: true }).click()
  const groupCard = page.getByRole('article', { name: 'Outbound group Browser manual exit', exact: true })
  await expect(groupCard).toBeVisible()
  await groupCard.getByRole('button', { name: 'Select Browser edge for Browser manual exit (TCP)', exact: true }).click()
  const group = (await list(page, 'outbound-groups')).find(item => item.name === 'Browser manual exit')
  expect(group).toBeDefined()
  await expect.poll(async () => {
    const selections = await list(page, `outbound-groups/${group!.id}/selection`)
    return selections.some(item => item.desired_node_id && item.applied_node_id === item.desired_node_id && item.observed_node_id === item.desired_node_id)
  }).toBe(true)
  await expect(groupCard.getByRole('table')).toContainText('Browser edge')
  const operations = await list(page, 'operations')
  expect(operations.some(item => item.action === 'selection' && item.status === 'applied')).toBe(true)
  await groupCard.getByLabel('Selection transport for Browser manual exit', { exact: true }).selectOption('udp')
  await groupCard.getByRole('button', { name: 'Select Browser edge for Browser manual exit (UDP)', exact: true }).click()
  await expect.poll(async () => (await list(page, `outbound-groups/${group!.id}/selection`)).map(item => item.scope.transport).sort()).toEqual(['tcp', 'udp'])
  await expect(groupCard.getByRole('table').getByRole('row').filter({ hasText: 'UDP' })).toContainText('Browser edge')
  await page.screenshot({ path: testInfo.outputPath('proxy-selection.png'), fullPage: true })
  await page.screenshot({ path: 'e2e/artifacts/proxy-selection-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(async () => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
  await expect(groupCard.getByRole('table').getByRole('row').filter({ hasText: 'TCP' })).toBeVisible()
  await expect(groupCard.getByRole('table').getByRole('row').filter({ hasText: 'UDP' })).toBeVisible()
  const scrollRegion = groupCard.locator('.table-scroll')
  const scrollMetrics = await scrollRegion.evaluate(element => ({ clientWidth: element.clientWidth, scrollWidth: element.scrollWidth }))
  expect(scrollMetrics.scrollWidth).toBeGreaterThan(scrollMetrics.clientWidth)
  const scrollLeft = await scrollRegion.evaluate(element => { element.scrollLeft = element.scrollWidth; return element.scrollLeft })
  expect(scrollLeft).toBeGreaterThan(0)
  await expect.poll(async () => {
    const cell = await groupCard.locator('tbody tr').first().locator('td').nth(2).boundingBox()
    const region = await scrollRegion.boundingBox()
    return !!cell && !!region && cell.x >= region.x && cell.x + cell.width <= region.x + region.width
  }).toBe(true)
  await groupCard.getByRole('combobox', { name: 'Selection transport for Browser manual exit', exact: true }).selectOption('tcp')
  await expect(groupCard.getByRole('button', { name: 'Select Browser edge for Browser manual exit (TCP)', exact: true })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('proxy-selection-mobile.png'), fullPage: true })
  await page.screenshot({ path: 'e2e/artifacts/proxy-selection-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('device and group forms preserve controller records after navigation', async ({ page, context }) => {
  await signIn(context)
  await page.goto('/')
  await navigate(page, 'Devices & Groups')
  await page.getByRole('button', { name: 'Add group', exact: true }).click()
  await page.getByLabel('Group name', { exact: true }).fill('Browser development group')
  await page.getByRole('combobox', { name: 'Group gateway', exact: true }).selectOption('fixture-gateway')
  await page.getByRole('combobox', { name: 'Group policy', exact: true }).selectOption('fixture-policy')
  await page.getByRole('button', { name: 'Save group', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edit group Browser development group', exact: true })).toBeVisible()
  const group = (await list(page, 'device-groups')).find(item => item.name === 'Browser development group')
  expect(group).toBeDefined()
  await page.getByRole('button', { name: 'Add device', exact: true }).click()
  await page.getByLabel('Device name', { exact: true }).fill('Browser build host')
  await page.getByRole('combobox', { name: 'Primary routing group', exact: true }).selectOption(group!.id)
  await page.getByLabel('IP addresses', { exact: true }).fill('192.0.2.73')
  await page.getByRole('button', { name: 'Save device', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edit device Browser build host', exact: true })).toBeVisible()
  const device = (await list(page, 'devices')).find(item => item.name === 'Browser build host')
  expect(device).toMatchObject({ primary_group_id: group!.id, enrollment_state: 'unenrolled', addresses: [expect.objectContaining({ address: '192.0.2.73' })] })
  await navigate(page, 'Overview')
  await navigate(page, 'Devices & Groups')
  await expect(page.getByRole('button', { name: 'Edit device Browser build host', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit device Browser build host', exact: true }).click()
  await page.getByLabel('Device name', { exact: true }).fill('Browser build host edited')
  await page.getByRole('button', { name: 'Save device', exact: true }).click()
  await expect.poll(async () => (await list(page, 'devices')).find(item => item.id === device!.id)?.name).toBe('Browser build host edited')
  const changed = (await list(page, 'devices')).find(item => item.id === device!.id)
  expect(changed!.revision).toBeGreaterThan(device!.revision)
})

test('policy editor compiles and explains a real controller manifest', async ({ page, context }) => {
  await signIn(context)
  await page.goto('/')
  await navigate(page, 'Rules')
  await page.getByRole('button', { name: 'New policy', exact: true }).click()
  await page.getByLabel('Policy name', { exact: true }).fill('Browser direct policy')
  await page.getByRole('button', { name: 'Save policy', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Policy revision')
  expect((await list(page, 'policies')).find(item => item.name === 'Browser direct policy')).toMatchObject({ default_action: { kind: 'direct' } })
  await page.getByLabel('Simulation gateway ID', { exact: true }).fill('fixture-gateway')
  await page.getByRole('button', { name: 'Compile preview', exact: true }).click()
  await expect(page.getByText('Compiler accepted', { exact: true })).toBeVisible()
  await page.getByLabel('Packet source IP', { exact: true }).fill('192.0.2.10')
  await page.getByRole('button', { name: 'Explain packet', exact: true }).click()
  await expect(page.getByText('Predicted: direct', { exact: true })).toBeVisible()
  await page.getByLabel('Packet source IP', { exact: true }).fill('198.51.100.2')
  await page.getByRole('button', { name: 'Explain packet', exact: true }).click()
  await expect(page.getByText('No prediction', { exact: true })).toBeVisible()
  await page.getByLabel('Packet source IP', { exact: true }).fill('192.0.2.10')
  const policy = (await list(page, 'policies')).find(item => item.name === 'Browser direct policy')!
  await page.getByRole('button', { name: 'Add rule', exact: true }).click()
  await page.getByLabel('Rule name', { exact: true }).fill('Block tracker')
  await page.getByRole('combobox', { name: 'Rule action', exact: true }).selectOption('block')
  await page.getByLabel('Domain suffixes', { exact: true }).fill('tracker.example')
  await page.getByLabel('Domain suffixes', { exact: true }).blur()
  await expect(page.getByText('Compiler accepted', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Predicted: direct', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Explain packet', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Save policy', exact: true }).click()
  await expect.poll(async () => (await list(page, 'policies')).find(item => item.id === policy.id)?.revision).toBeGreaterThan(policy.revision)
  await page.getByRole('button', { name: 'Compile preview', exact: true }).click()
  await expect(page.getByText('Compiler accepted', { exact: true })).toBeVisible()
  await page.getByLabel('Packet domain', { exact: true }).fill('tracker.example')
  await page.getByRole('button', { name: 'Explain packet', exact: true }).click()
  await expect(page.getByText('Predicted: block', { exact: true })).toBeVisible()
})

test('failed gateway publication keeps the staged revision and shows the error', async ({ page, context }) => {
  await signIn(context)
  await page.goto('/')
  await navigate(page, 'Subscriptions')
  await page.getByRole('button', { name: 'Add subscription', exact: true }).click()
  await page.getByLabel('Provider name', { exact: true }).fill('Browser publication-failure')
  await page.getByRole('combobox', { name: 'Source type', exact: true }).selectOption('paste')
  await page.getByLabel('Subscription content', { exact: true }).fill('socks5://fixture:password@failed-edge.example:1080#Unpublished%20edge')
  await page.getByRole('combobox', { name: 'Import format', exact: true }).selectOption('links')
  await page.getByRole('button', { name: 'Add and stage provider', exact: true }).click()
  const card = page.getByRole('article', { name: 'Provider Browser publication-failure', exact: true })
  await expect(card.getByRole('button', { name: 'Apply staged revision', exact: true })).toBeEnabled()
  await card.getByRole('button', { name: 'Apply staged revision', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('provider publication was not confirmed by gateway readback')
  const provider = (await list(page, 'providers')).find(item => item.name === 'Browser publication-failure')!
  const revisions = await list(page, `providers/${provider.id}/revisions`)
  expect(revisions).toHaveLength(1)
  expect(revisions[0]!.state).toBe('staged')
  await expect(card.getByRole('button', { name: 'Apply staged revision', exact: true })).toBeEnabled()
})

test('gateway registration reads back without inventing runtime health', async ({ page, context }) => {
  await signIn(context)
  await page.goto('/')
  await navigate(page, 'Infrastructure')
  await page.getByRole('button', { name: 'Register gateway', exact: true }).click()
  await page.getByLabel('Gateway name', { exact: true }).fill('Browser registered gateway')
  await page.getByLabel('Gateway endpoint', { exact: true }).fill('https://browser-gateway.invalid:8443')
  await page.getByLabel('Adapter', { exact: true }).fill('dae')
  await page.getByRole('button', { name: 'Save gateway', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser registered gateway', exact: true })).toBeVisible()
  const gateway = (await list(page, 'gateways')).find(item => item.name === 'Browser registered gateway')!
  expect(gateway).toMatchObject({ endpoint: 'https://browser-gateway.invalid:8443/', adapter: 'dae', revision: 1 })
  const card = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Browser registered gateway', exact: true }) })
  await expect(card.getByText('unknown', { exact: true })).toBeVisible()
})

test('reusable rule sets save revisions and compile when referenced by a policy', async ({ page, context }) => {
  await signIn(context)
  await page.goto('/')
  await navigate(page, 'Rules')
  await page.getByRole('button', { name: 'New rule set', exact: true }).click()
  await page.getByLabel('Rule set name', { exact: true }).fill('Browser reusable blocks')
  await page.getByRole('button', { name: 'Add rule', exact: true }).click()
  await page.getByLabel('Rule name', { exact: true }).fill('Reusable tracker block')
  await page.getByRole('combobox', { name: 'Rule action', exact: true }).selectOption('block')
  await page.getByLabel('Domain suffixes', { exact: true }).fill('shared-tracker.example')
  await page.getByLabel('Domain suffixes', { exact: true }).blur()
  await page.getByRole('button', { name: 'Save rule set', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Rule set revision')
  const ruleSet = (await list(page, 'rule-sets')).find(item => item.name === 'Browser reusable blocks')!
  expect(ruleSet.rules[0]).toMatchObject({ action: { kind: 'block' }, match: { domain_suffix: ['shared-tracker.example'] } })
  await page.getByLabel('Rule set name', { exact: true }).fill('Browser reusable blocks revised')
  await page.getByRole('button', { name: 'Save rule set', exact: true }).click()
  await expect.poll(async () => (await list(page, 'rule-sets')).find(item => item.id === ruleSet.id)?.revision).toBeGreaterThan(ruleSet.revision)
  await expect(page.getByRole('status')).toContainText('Rule set revision')
  await page.screenshot({ path: 'e2e/artifacts/rule-set-editor-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'New policy', exact: true }).click()
  await page.getByLabel('Policy name', { exact: true }).fill('Browser shared block policy')
  await page.getByRole('button', { name: 'Add rule set', exact: true }).click()
  await page.getByRole('combobox', { name: 'Referenced rule set', exact: true }).selectOption(ruleSet.id)
  await page.getByRole('button', { name: 'Save policy', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Policy revision')
  await page.getByLabel('Simulation gateway ID', { exact: true }).fill('fixture-gateway')
  await page.getByRole('button', { name: 'Compile preview', exact: true }).click()
  await expect(page.getByText('Compiler accepted', { exact: true })).toBeVisible()
  await page.getByLabel('Packet domain', { exact: true }).fill('shared-tracker.example')
  await page.getByRole('button', { name: 'Explain packet', exact: true }).click()
  await expect(page.getByText('Predicted: block', { exact: true })).toBeVisible()
})

test('group draft survives navigation while a missing policy is created', async ({ page, context }) => {
  await signIn(context)
  await page.goto('/')
  await navigate(page, 'Devices & Groups')
  await page.getByRole('button', { name: 'Add group', exact: true }).click()
  await page.getByLabel('Group name', { exact: true }).fill('Browser preserved group draft')
  await page.getByRole('combobox', { name: 'Group gateway', exact: true }).selectOption('fixture-gateway')
  await navigate(page, 'Rules')
  await page.getByRole('button', { name: 'New policy', exact: true }).click()
  await page.getByLabel('Policy name', { exact: true }).fill('Browser new dependency policy')
  await page.getByRole('button', { name: 'Save policy', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Policy revision')
  const policy = (await list(page, 'policies')).find(item => item.name === 'Browser new dependency policy')!
  await navigate(page, 'Devices & Groups')
  await expect(page.getByLabel('Group name', { exact: true })).toHaveValue('Browser preserved group draft')
  await expect(page.getByRole('combobox', { name: 'Group gateway', exact: true })).toHaveValue('fixture-gateway')
  await page.getByRole('combobox', { name: 'Group policy', exact: true }).selectOption(policy.id)
  await page.getByRole('button', { name: 'Save group', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edit group Browser preserved group draft', exact: true })).toBeVisible()
  expect((await list(page, 'device-groups')).find(item => item.name === 'Browser preserved group draft')).toMatchObject({ policy_id: policy.id, gateway_id: 'fixture-gateway' })
})
