import { expect, test } from '@playwright/test'
import { signIn } from './auth'

test('Used by follows stored rule-set and device-group references to exact editors', async ({ page, context }) => {
  await signIn(context)
  const csrf = (await context.cookies()).find(cookie => cookie.name === 'egressdeck_csrf')!.value
  const create = async (path: string, data: unknown) => {
    const response = await page.request.post(`/api/v1/${path}`, { headers: { 'X-CSRF-Token': csrf }, data })
    expect(response.status(), await response.text()).toBe(201)
    return response.json()
  }
  const provider = await create('providers', { name: 'Usage node source', source: 'inline', format: 'local', fetch_route: 'direct' })
  const staged = await page.request.post(`/api/v1/providers/${provider.id}/stage`, { headers: { 'X-CSRF-Token': csrf, 'Idempotency-Key': 'usage-stage-1' }, data: { content: 'socks5://user:pass@usage-node.example:1080#Usage%20node', format: 'links' } })
  expect(staged.status(), await staged.text()).toBe(202)
  const inventory = await page.request.get('/api/v1/nodes')
  const node = (await inventory.json()).items.find((item: { provider_id: string }) => item.provider_id === provider.id)
  expect(node).toBeDefined()
  const outbound = await create('outbound-groups', { name: 'Usage browser exit', gateway_id: 'fixture-gateway', node_ids: [node.id], mode: 'manual', replacement_policy: 'block' })
  const ruleSet = await create('rule-sets', { name: 'Usage shared routes', rules: [{ id: 'usage-rule', name: 'Usage service', enabled: true, match: { domain_suffix: ['usage.example'] }, action: { kind: 'outbound_group', outbound_group_id: outbound.id } }] })
  const policy = await create('policies', { name: 'Usage browser policy', entries: [{ rule_set_id: ruleSet.id }], default_action: { kind: 'direct' }, unknown_domain_action: { kind: 'direct' }, proxy_failure_action: { kind: 'block' } })
  const group = await create('device-groups', { name: 'Usage browser devices', gateway_id: 'fixture-gateway', policy_id: policy.id, enabled: true })
  await page.goto('/#/proxies')
  await page.getByRole('button', { name: 'New outbound group', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Selection mode', exact: true }).locator('option[value="automatic"]')).toHaveAttribute('disabled', '')
  await page.getByLabel('Outbound group name', { exact: true }).fill('Usage filtered exit')
  await page.getByRole('combobox', { name: 'Outbound gateway', exact: true }).selectOption('fixture-gateway')
  await page.getByRole('combobox', { name: 'Candidate source', exact: true }).selectOption('filters')
  await page.getByLabel('Included provider IDs', { exact: true }).fill(provider.id)
  await page.getByLabel('Included protocols', { exact: true }).fill('socks5')
  await page.getByLabel('Included exact node names', { exact: true }).fill('Usage node')
  await expect(page.getByText('Local preview from the loaded inventory:', { exact: false })).toContainText('1 supported candidates')
  await page.getByRole('button', { name: 'Create outbound group', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Outbound group Usage filtered exit' })).toContainText('Candidates follow saved source filters')
  const groupResponse = await page.request.get('/api/v1/outbound-groups')
  const filtered = (await groupResponse.json()).items.find((item: { name: string }) => item.name === 'Usage filtered exit')
  expect(filtered).toMatchObject({ node_ids: [node.id], source_filters: { provider_ids: [provider.id], protocols: ['socks5'], include_names: ['Usage node'] } })
  const usage = page.getByRole('region', { name: 'Used by Usage browser exit' })
  await expect(usage.getByRole('link', { name: 'Rule set: Usage shared routes', exact: true })).toBeVisible()
  await expect(usage.getByRole('link', { name: 'Policy: Usage browser policy', exact: true })).toBeVisible()
  await expect(usage.getByRole('link', { name: 'Device group: Usage browser devices', exact: true })).toBeVisible()

  await usage.getByRole('link', { name: 'Rule set: Usage shared routes', exact: true }).click()
  await expect(page.getByLabel('Rule set name', { exact: true })).toHaveValue('Usage shared routes')
  await expect(page.getByLabel('Rule name', { exact: true })).toHaveValue('Usage service')
  await page.getByRole('navigation').getByRole('button', { name: 'Proxies', exact: false }).click()
  await usage.getByRole('link', { name: 'Policy: Usage browser policy', exact: true }).click()
  await expect(page.getByLabel('Policy name', { exact: true })).toHaveValue('Usage browser policy')
  await page.getByRole('navigation').getByRole('button', { name: 'Proxies', exact: false }).click()
  await usage.getByRole('link', { name: 'Device group: Usage browser devices', exact: true }).click()
  const groupCard = page.locator(`[id="device-group-${group.id}"]`)
  await expect(groupCard).toHaveClass(/row-card--linked/)
  await expect(groupCard.getByRole('button', { name: 'Edit group Usage browser devices', exact: true })).toBeVisible()
})
