apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: egressdeck-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - gateway-agent-deployment.yaml
  - gateway-agent-service.yaml
  - networkpolicy.yaml
